### ISSUE TITLE
Well Done!

### ISSUE THREAD

**Issue by miahbates** [fac-23/preA-testing-week2-adampaolo#27]
We loved your to-do list, you both did a fab job! ✨ 

We thought these were great:
- background colour change when the item was completed
- use of aria role to increase accessibility. 
- loved the layout and how variable, functions and event listeners were split up - made it easier to read.
- like the filter button which hides completed items. 

Not much to improve as we thought we thought it was great, interested to see what you will do with 'bubble event issue'..

**Comment by paologhidoni** [comment]
Thank you!! 🙌🏻
